# Copyright (c) 2017-2019 Carnegie Mellon University. All rights reserved.
# Use of this source code is governed by BSD 3-clause license.

version: '3.1'
services:
  storage:
    build: ../storage
    command: ["-db", "edusense", "-dbhost", "mongo", "-port", "5000"]
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - edusense_frontend
      - edusense_backend
    secrets:
      - ssl_cert
      - ssl_cert_private_key
      - app_username
      - app_password
  mongo:
    image: mongo
    volumes:
      - edusense-db-data:/data/db
    ports:
      - "27018:27017"
    networks:
      - edusense_backend
      - connector

  storage_dev:
    build: ../storage
    command: ["-db", "edusense", "-dbhost", "mongo_dev", "-port", "5001"]
    ports:
      - "5001:5001"
    depends_on:
      - mongo_dev
    networks:
      - edusense_frontend_dev
      - edusense_backend_dev
    secrets:
      - ssl_cert
      - ssl_cert_private_key
      - app_username
      - app_password
  mongo_dev:
    image: mongo
    volumes:
      - edusense-db-data-dev:/data/db
    ports:
      - "27019:27017"
    networks:
      - edusense_backend_dev
      - connector
networks:
  edusense_frontend:
    driver: bridge
    internal: false
  edusense_backend:
    driver: bridge
    internal: true

  edusense_frontend_dev:
    driver: bridge
    internal: false
  edusense_backend_dev:
    driver: bridge
    internal: true
  connector:
    driver: bridge
    internal: false
secrets:
  ssl_cert:
    file: /run/secrets/ssl_cert
  ssl_cert_private_key:
    file: /run/secrets/ssl_cert_private_key
  app_username:
    file: /run/secrets/app_username
  app_password:
    file: /run/secrets/app_password


volumes:
  edusense-db-data:
  edusense-db-data-dev: